name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  run_unit_and_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: Install Yarn dependencies
        working-directory: ./packages/app
        run: yarn install
      - name: Run test
        working-directory: ./packages/app
        run: yarn test
      - name: Run build
        working-directory: ./packages/app
        run: yarn build
      - name: Perform e2e tests with Heaful Puppeteer
        uses: maufrontier/puppeteer-headful@v3
        env:
          CI: 'true'
        with:
          commands: |
            cd packages/app
            yarn run serve -s dist -p 3000 &
            sleep 5
            yarn run jest ./tests/e2e-ui*.test.*
      
