name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  run_unit_and_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn dependencies
        run: yarn --cwd install
      - name: Run test
        run: yarn --cwd packages/app test
      - name: Run build
        run: yarn --cwd packages/app build
      - name: Run e2e tests
        run: yarn --cwd packages/app test:e2e-ui
      
