name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  run_twitter_circuit_tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: echo ${{vars.ALCHEMY_API_KEY}}
